### PR TITLE
Fix mobile preferences page

### LINKED ISSUE #33: Error opening offer template panel
So I mangled up my server a bit because I decided to move to port 443. However, I'm having some difficulty updating my clients. When I went to the tab in preferences to set up the app, I got an error, and the following in the grain log:

```
2022/07/02 08:19:10 Called Connect()
2022/07/02 08:19:10 New connection (#3)
2022/07/02 08:19:10 Receiving pb messages.
2022/07/02 08:19:12 Reading from websocket: websocket: close 1001 (going away)
2022/07/02 08:19:12 ceasing to receive pb messages
2022/07/02 08:19:12 Connection #3 closed
2022/07/02 08:19:13 [error] 82#82: *375 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of Pref_Mobile::csrf_ignore($method) must be compatible with Handler::csrf_ignore(string $method): bool in /opt/app/classes/pref/mobile.php on line 2" while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "GET /backend.php?op=pref-mobile HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "ui-45fab915561ff07ef23dcba6f9586df1.ocdhost.sandcats.io"
```

I suspect the fix is right here: https://github.com/zenhack/ttrss-sandstorm/commit/987870074bd17e24c52e51abddfaf48d63ed2f09

### PR DESCRIPTION
**Pull request by ocdtrekkie**
This PR fixes #33.

My previous PR on this, #34, was close, but no cigar: I copied the entire csrf_ignore() function from a standard prefs page, and that got this page loading. However, the offer templates also didn't load, because the script is onload()'d by an image file that has moved. Changing the image fixed that as well.

Note that this is NOT tested against the php-from-nix branch yet, which I haven't looked at since you said it had other breakage.

### CODE REVIEW

File: classes/pref/mobile.php [hunk 1]
```diff
@@ -1,8 +1,10 @@
 <?php
 class Pref_Mobile extends Handler_Protected {
-    function csrf_ignore($method) {
-        return $method === "index";
-    }
+    function csrf_ignore(string $method): bool {
+		$csrf_ignored = array("index");
+
+		return array_search($method, $csrf_ignored) !== false;
+	}
```
Comment (zenhack) [inline classes/pref/mobile.php]: Indentation.

File: classes/pref/mobile.php [hunk 2]
```diff
@@ -22,7 +24,7 @@ function index() {
   <li>Tiny Tiny RSS Reader on the <a href="https://apps.microsoft.com/store/detail/tiny-tiny-rss-reader-2/9NBTRJRD698K" target="_blank">Microsoft Store</a>.</li>
 </ul>
 
-<img src="/images/logo_small.png" onload='var script = document.createElement("script");script.type = "text/javascript"; script.src   = "/js/sandstorm-offer-template.js"; document.body.appendChild(script);'></img>
+<img src="/images/favicon.png" onload='var script = document.createElement("script");script.type = "text/javascript"; script.src   = "/js/sandstorm-offer-template.js"; document.body.appendChild(script);'></img>
```
Comment (zenhack) [inline classes/pref/mobile.php:27]: Is this related to the fix in some way I'm missing?

If not, I'd prefer to leave it out, just because I'd like to be doing as little patching of upstream as possible.

**Review by zenhack — CHANGES_REQUESTED** [review]
Some minor comments, but I can confirm it works! thanks for tackling this.

File: classes/pref/mobile.php (hunk 2 above)
Comment (ocdtrekkie) [reply classes/pref/mobile.php:27]: So the entire mobile.php file is Sandstorm-specific, I believe. We're not modifying upstream here at all. (This is why this broke in the first place, upstream changed but mobile.php, not existing upstream, did not get updated when the rest of the panels did.)

Without this fix, because logo_small.png no longer exists in the repo, the onload= here does not fire, and hence offer templates do not populate on the page.

File: classes/pref/mobile.php (hunk 1 above)
Comment (ocdtrekkie) [reply classes/pref/mobile.php]: This was a spaces vs. tabs crime, it looked fine on my machine.

**Review by zenhack — APPROVED** [review]

File: classes/pref/mobile.php (hunk 1 above)
Comment (zenhack) [reply classes/pref/mobile.php]: I figured it was something like that
